
export const LOGIN_REQUEST='LOGIN_REQUEST'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_FAILURE='LOGIN_FAILURE'

export const SIGN_UP_REQUEST='SIGN_UP_REQUEST'
export const SIGN_UP_SUCCESS='SIGN_UP_SUCCESS'
export const SIGN_UP_FAILURE='SIGN_UP_FAILURE'

export const GET_USER_DETAILS_REQUEST='GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_SUCCESS='GET_USER_DETAILS_SUCCESS'
export const GET_USER_DETAILS_FAILURE='GET_USER_DETAILS_FAILURE'

export const HANDLE_KEYS='HANDLE_KEYS'

export const RESET_REDUCER='RESET_REDUCER'
